run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - bodyclose
    - noctx

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/user/openclaw-go
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: internal/gateway/protocol/
      linters:
        - unused  # Schema 定义可能暂时未使用
